export const dataCards = [
  {
    id: '00',
    name: 'Bita',
    backgroundImg: require('../../assets/images/bita.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '01',
    name: 'Dan',
    backgroundImg: require('../../assets/images/dan.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '02',
    name: 'Tito',
    backgroundImg: require('../../assets/images/tito.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '03',
    name: 'Lila',
    backgroundImg: require('../../assets/images/lila.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '04',
    name: 'Dino',
    backgroundImg: require('../../assets/images/dino.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '05',
    name: 'Birds',
    backgroundImg: require('../../assets/images/birds.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '06',
    name: 'Vaca',
    backgroundImg: require('../../assets/images/vaca.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '07',
    name: 'Sol',
    backgroundImg: require('../../assets/images/sol.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '08',
    name: 'Star',
    backgroundImg: require('../../assets/images/star.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '09',
    name: 'Mundo',
    backgroundImg: require('../../assets/images/mundo.png'),
    match: false,
    isFaceUp: false,
  },

  {
    id: '10',
    name: 'Bita',
    backgroundImg: require('../../assets/images/bita.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '11',
    name: 'Dan',
    backgroundImg: require('../../assets/images/dan.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '12',
    name: 'Tito',
    backgroundImg: require('../../assets/images/tito.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '13',
    name: 'Lila',
    backgroundImg: require('../../assets/images/lila.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '14',
    name: 'Dino',
    backgroundImg: require('../../assets/images/dino.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '15',
    name: 'Birds',
    backgroundImg: require('../../assets/images/birds.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '16',
    name: 'Vaca',
    backgroundImg: require('../../assets/images/vaca.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '17',
    name: 'Sol',
    backgroundImg: require('../../assets/images/sol.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '18',
    name: 'Star',
    backgroundImg: require('../../assets/images/star.png'),
    match: false,
    isFaceUp: false,
  },
  {
    id: '19',
    name: 'Mundo',
    backgroundImg: require('../../assets/images/mundo.png'),
    match: false,
    isFaceUp: false,
  },
];
